export const tarot = [
  { name: "0 - The Fool", url: "/images/tarot/1 The Fool.png" },
  { name: "9 - The Hermit", url: "/images/tarot/10 The Hermit.png" },
  {
    name: "10 - Wheel of Fortune",
    url: "/images/tarot/11 Wheel of Fortune.png",
  },
  { name: "11 - Justice", url: "/images/tarot/12 Justice.png" },
  { name: "12 - The Hanged Man", url: "/images/tarot/13 The Hanged Man.png" },
  { name: "13 - Death", url: "/images/tarot/14 Death.png" },
  { name: "14 - Temperance", url: "/images/tarot/15 Temperance.png" },
  { name: "15 - The Devil", url: "/images/tarot/16 The Devil.png" },
  { name: "16 - The Tower", url: "/images/tarot/17 The Tower.png" },
  { name: "17 - The Star", url: "/images/tarot/18 The Star.png" },
  { name: "18 - The Moon", url: "/images/tarot/19 The moon.png" },
  { name: "1 - The Magician", url: "/images/tarot/2 The Magician.png" },
  { name: "19 - The Sun", url: "/images/tarot/20 The Sun.png" },
  { name: "20 - Judgement", url: "/images/tarot/21 Judgement.png" },
  { name: "21 - The World", url: "/images/tarot/22 The World.png" },
  {
    name: "Ace of Pentacles",
    url: "/images/tarot/23 Ace of Pentacles.png",
  },
  { name: "Two of Pentacles", url: "/images/tarot/24 Two of Pentacles.png" },
  {
    name: "Three of Pentacles",
    url: "/images/tarot/25 Three of Pentacles.png",
  },
  { name: "Four of Pentacles", url: "/images/tarot/26 Four of Pentacles.png" },
  { name: "Five of Pentacles", url: "/images/tarot/27 Five of Pentacles.png" },
  { name: "Six of Pentacles", url: "/images/tarot/28 Six of Pentacles.png" },
  {
    name: "Seven of Pentacles",
    url: "/images/tarot/29 Seven of Pentacles.png",
  },
  {
    name: "2 - The High Priestess",
    url: "/images/tarot/3 The High Priestess.png",
  },
  {
    name: "Eight of Pentacles",
    url: "/images/tarot/30 Eight of Pentacles.png",
  },
  { name: "Nine of Pentacles", url: "/images/tarot/31 Nine of Pentacles.png" },
  { name: "Ten of Pentacles", url: "/images/tarot/32 Ten of Pentacles.png" },
  { name: "Page of Pentacles", url: "/images/tarot/33 Page of Pentacles.png" },
  {
    name: "Knight of Pentacles",
    url: "/images/tarot/34 Knight of Pentacles.png",
  },
  {
    name: "Queen of Pentacles",
    url: "/images/tarot/35 Queen of Pentacles.png",
  },
  { name: "King of Pentacles", url: "/images/tarot/36 King of Pentacles.png" },
  { name: "Ace of Wands", url: "/images/tarot/37 Ace of Wands.png" },
  { name: "Two of Wands", url: "/images/tarot/38 Two of Wands.png" },
  { name: "Three of Wands", url: "/images/tarot/39 Three of Wands.png" },
  { name: "3 - The Empress", url: "/images/tarot/4 The Empress.png" },
  { name: "Four of Wands", url: "/images/tarot/40 Four of Wands.png" },
  { name: "Five of Wands", url: "/images/tarot/41 Five of Wands.png" },
  { name: "Six of Wands", url: "/images/tarot/42 Six of Wands.png" },
  { name: "Seven of Wands", url: "/images/tarot/43 Seven of Wands.png" },
  { name: "Eight of Wands", url: "/images/tarot/44 Eight of Wands.png" },
  { name: "Nine of Wands", url: "/images/tarot/45 Nine of Wands.png" },
  { name: "Ten of Wands", url: "/images/tarot/46 Ten of Wands.png" },
  { name: "Page of Wands", url: "/images/tarot/47 Page of Wands.png" },
  { name: "Knight of Wands", url: "/images/tarot/48 Knight of Wands.png" },
  { name: "Queen of Wands", url: "/images/tarot/49 Queen of Wands.png" },
  { name: "4 - The Emperor", url: "/images/tarot/5 The Emperor.png" },
  { name: "King of Wands", url: "/images/tarot/50 King of Wands.png" },
  { name: "Ace of Cups", url: "/images/tarot/51 Ace of Cups.png" },
  { name: "Two of Cups", url: "/images/tarot/52 Two of Cups.png" },
  { name: "Three of Cups", url: "/images/tarot/53 Three of Cups.png" },
  { name: "Four of Cups", url: "/images/tarot/54 Four of Cups.png" },
  { name: "Five of Cups", url: "/images/tarot/55 Five of Cups.png" },
  { name: "Six of Cups", url: "/images/tarot/56 Six of Cups.png" },
  { name: "Seven of Cups", url: "/images/tarot/57 Seven of Cups.png" },
  { name: "Eight of Cups", url: "/images/tarot/58 Eight of Cups.png" },
  { name: "Nine of Cups", url: "/images/tarot/59 Nine of Cups.png" },
  { name: "5 - The Hierophant", url: "/images/tarot/6 The Hierophant.png" },
  { name: "Ten of Cups", url: "/images/tarot/60 Ten of Cups.png" },
  { name: "Page of Cups", url: "/images/tarot/61 Page of Cups.png" },
  { name: "Knight of Cups", url: "/images/tarot/62 Knight of Cups.png" },
  { name: "Queen of Cups", url: "/images/tarot/63 Queen of Cups.png" },
  { name: "King of Cups", url: "/images/tarot/64 King of Cups.png" },
  { name: "Ace of Swords", url: "/images/tarot/65 Ace of Swords.png" },
  { name: "Two of Swords", url: "/images/tarot/66 Two of Swords.png" },
  { name: "Three of Swords", url: "/images/tarot/67 Three of Swords.png" },
  { name: "Four of Swords", url: "/images/tarot/68 Four of Swords.png" },
  { name: "Five of Swords", url: "/images/tarot/69 Five of Swords.png" },
  { name: "6 - The Lovers", url: "/images/tarot/7 The Lovers.png" },
  { name: "Six of Swords", url: "/images/tarot/70 Six of Swords.png" },
  { name: "Seven of Swords", url: "/images/tarot/71 Seven of Swords.png" },
  { name: "Eight of Swords", url: "/images/tarot/72 Eight of Swords.png" },
  { name: "Nine of Swords", url: "/images/tarot/73 Nine of Swords.png" },
  { name: "Ten of Swords", url: "/images/tarot/74 Ten of Swords.png" },
  { name: "Page of Swords", url: "/images/tarot/75 Page of Swords.png" },
  { name: "Knight of Swords", url: "/images/tarot/76 Knight of Swords.png" },
  { name: "Queen of Swords", url: "/images/tarot/77 Queen of Swords.png" },
  { name: "King of Swords", url: "/images/tarot/78 King of Swords.png" },
  { name: "7 - The Chariot", url: "/images/tarot/8 The Chariot.png" },
  { name: "8 - Strength", url: "/images/tarot/9 Strength.png" },
];
